---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin = 1in

title: "CV"
author: Joseph T. Lariscy

jobtitle: "Associate Professor, Department of Sociology, University of Memphis"
address: "223 Clement Hall · Memphis, TN 38152"
fontawesome: yes
email: joseph.lariscy@memphis.edu
# phone: (901) 678-2612
github: josephlariscy
# twitter: JosephLariscy
# web: josephlariscy.com
# updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue

# I removed code from the file svm-latex-cv.tex that put page numbers in the
# bottom right corner. I like one page number at the bottom. Before I cut
# the code there was a second page number in the bottom right corner in the
# form 2/11.
---

# Employment

*University of Memphis*

\setlength{\leftskip}{1cm}
| Associate Professor, Department of Sociology \hfill 2021--present
| Assistant Professor, Department of Sociology \hfill 2015--2021
| Director of Graduate Studies, Department of Sociology \hfill 2020--present
\setlength{\leftskip}{0pt}

*Duke University*

\setlength{\leftskip}{1cm}
| NIA Postdoctoral Fellow, Duke Population Research Institute \hfill 2013&ndash;2015
\setlength{\leftskip}{0pt}

*University of Texas at Austin*

\setlength{\leftskip}{1cm}
| Doctoral Trainee,  Population Research Center \hfill 2007&ndash;2013
\setlength{\leftskip}{0pt}

# Education

PhD &nbsp; &nbsp;Sociology &nbsp; &nbsp; University of Texas at Austin \hfill 2013  
MA &nbsp; &nbsp; Sociology &nbsp; &nbsp; University of Texas at Austin \hfill 2009  
BA &nbsp; &nbsp; &nbsp;Sociology &nbsp; &nbsp; University of Georgia \hfill 2007

# Publications
\* = student coauthor

Lariscy, Joseph T. (Forthcoming). [Demographic Methods.](https://osf.io/preprints/socarxiv/mc6hv/) In *The Wiley-Blackwell Encyclopedia of Health, Illness, Behavior, and Society, Second Edition.* William C. Cockerham, Jonathan Gabe, Stella Quah, and J. Michael Ryan (eds.). Wiley.

Brown, Dustin C., Joseph T. Lariscy, and Benjamin H. Walker. (2023). [State-Level Trends in Lifespan Variability in the United States, 1960–2019: A Research Note.](https://read.dukeupress.edu/demography/article/doi/10.1215/00703370-10423884/342894/State-Level-Trends-in-Lifespan-Variability-in-the) *Demography* 60(1): 1–14.

Vogelsang, Eric M. and Joseph T. Lariscy. (2020). [Let’s Drink to Being Socially Active: Family Characteristics, Social Participation, and Alcohol Abuse across Mid- and Later-Life.](https://journals.sagepub.com/doi/full/10.1177/0022146520962456) *Journal of Health and Social Behavior* 61(4): 453–469.

Fatema,* Kaniz and Joseph T. Lariscy. (2020). [Mass Media Exposure and Maternal Healthcare Utilization in South Asia](https://www.sciencedirect.com/science/article/pii/S2352827320302512). *Social Science & Medicine–Population Health* 11: 100614.

Lariscy, Joseph T., Robert A. Hummer, and Richard G. Rogers. (2020). [Lung Cancer Mortality among Never-Smokers in the United States: Estimating Smoking-Attributable Mortality with Nationally Representative Data](https://www.sciencedirect.com/science/article/pii/S1047279720301393). *Annals of Epidemiology* 45: 5–11.

Lariscy, Joseph T., Samia Tasmim,* and Sarah Collins.* (2020). [Racial and Ethnic Disparities in Health](https://www.researchgate.net/publication/342352707_Racial_and_Ethnic_Disparities_in_Health). In *Encyclopedia of Gerontology and Population Aging*. Danan Gu and Matthew E. Dupre (eds.). Springer Nature Switzerland AG.

Brown, Dustin C., Joseph T. Lariscy, and Lucie Kalousová. (2019). [Comparability of Mortality Estimates from Social Surveys and Vital Statistics Data in the United States](https://link.springer.com/article/10.1007/s11113-018-9505-1). *Population Research and Policy Review* 38(3): 371–401.

Lariscy, Joseph T. (2019). [Smoking-Attributable Mortality by Cause of Death in the United States: An Indirect Approach](https://www.sciencedirect.com/science/article/pii/S2352827318302118?via%3Dihub). *Social Science & Medicine–Population Health* 7: 100349.

Lariscy, Joseph T., Robert A. Hummer, and Richard G. Rogers. (2018). [Cigarette Smoking and All-Cause and Cause-Specific Adult Mortality in the United States](https://read.dukeupress.edu/demography/article/55/5/1855/167925/Cigarette-Smoking-and-All-Cause-and-Cause-Specific). *Demography* 55(5): 1855–1885.

Lariscy, Joseph T. (2017). [Black-White Disparities in Adult Mortality: Implications of Differential Record Linkage for Understanding the Mortality Crossover](https://link.springer.com/article/10.1007/s11113-016-9415-z). *Population Research and Policy Review* 36(1): 137–156.

Lariscy, Joseph T., Claudia Nau, Glenn Firebaugh, and Robert A. Hummer. (2016). [Hispanic White Differences in Lifespan Variability in the United States](https://read.dukeupress.edu/demography/article/53/1/215/167323/Hispanic-White-Differences-in-Lifespan-Variability). *Demography* 53(1): 215–239.

Lariscy, Joseph T., Robert A. Hummer, and Mark D. Hayward. (2015). [Hispanic Older Adult Mortality in the United States: New Estimates and an Assessment of Factors Shaping the Hispanic Paradox](https://read.dukeupress.edu/demography/article/52/1/1/169365/Hispanic-Older-Adult-Mortality-in-the-United). *Demography* 52(1): 1–14.

Gorman, Bridget K., Joseph T. Lariscy, and Charisma Kaushik.* (2014). [Gender, Acculturation, and Smoking Behaviors among U.S. Asian and Latino Immigrants](https://www.sciencedirect.com/science/article/pii/S0277953614000999?via%3Dihub). *Social Science & Medicine* 106: 110–118.

Lariscy, Joseph T., Robert A. Hummer, Jessica M. Rath, Andrea C. Villanti, Mark D. Hayward, and Donna M. Vallone. (2013). [Race/Ethnicity, Nativity, and Tobacco Use among U.S. Young Adults: Results from a Nationally-Representative Survey](https://academic.oup.com/ntr/article/15/8/1417/1283744). *Nicotine & Tobacco Research* 15(8): 1417–1426.

Wade,* Becky, Joseph T. Lariscy, and Robert A. Hummer. (2013). [Racial/Ethnic and Nativity Patterns of U.S. Adolescent and Young Adult Smoking](https://link.springer.com/article/10.1007/s11113-013-9275-8). *Population Research and Policy Review* 32(3): 353–371.

Lariscy, Joseph T. (2011). [Differential Record Linkage by Hispanic Ethnicity and Age in Linked Mortality Studies: Implications for the Epidemiologic Paradox](https://journals.sagepub.com/doi/full/10.1177/0898264311421369). *Journal of Aging and Health* 23(8): 1263–1284.

Hummer, Robert A. and Joseph T. Lariscy. (2011). [Educational Attainment and Adult Mortality](https://www.researchgate.net/publication/216839888_Educational_Attainment_and_Adult_Mortality). Chapter 12 (Pp. 241–262) in *International Handbook of Adult Mortality*. Richard G. Rogers and Eileen M. Crimmins (eds). Dordrecht, The Netherlands: Springer.

# Revise and Resubmit

Lariscy, Joseph T. and Israt Jahan.* Gender-Specific Trends in Educational Attainment and Self-Rated Health, 1972–2018. Revise and Resubmit at *Biodemography and Social Biology.*

# Papers in Preparation

Lariscy, Joseph T and Aggie Yellow Horse. Cause-of-Death Contributions to the Hispanic Mortality Paradox.

Lariscy, Joseph T. and Eric M. Vogelsang. Racial/Ethnic Disparities in Lifespan Variability: Estimates from Adjusted U.S. Life Tables for Five Racial/Ethnic Populations in 2019 and 2020.

# Grants

*Delta Revitalization through Innovation, Vision, and Equity (DRIVE)*. Subcontractor, Joseph Lariscy. Funded by the Delta Regional Authority. $40,000. 2023.

# Invited Presentations

"State-Level Trends in Lifespan Variability in the United States, 1960--2019." Department of Sociology and Center for Family and Demographic Research, Bowling Green State University, May 2, 2022

“Cigarette Smoking and Cause-Specific Adult Mortality in the United States.” Federal Statistical Research Data Center (FSRDC) Presentation Series (virtual), September 22, 2021

“State-Level Trends in Lifespan Variability in the United States, 1960–2014.” New Perspectives on Lifespan Inequality webinar (virtual), Southern Denmark University. January 21, 2021

“Lung Cancer Mortality among Nonsmokers: Estimating Smoking-Attributable Mortality with Nationally-Representative Data.” Social Science Research Institute, Duke University. April 26, 2019

“Cigarette Smoking and Cause-Specific Adult Mortality in the United States.” Department of Sociology and Center for Demography and Population Health, Florida State University. November 30, 2017

“Cigarette Smoking and Cause-Specific Adult Mortality in the United States.” Department of Sociology and Aging Studies Institute, Syracuse University. February 21, 2017

“Hispanic-White Disparities in Lifespan Variability in the United States.” Department of Sociology, Vanderbilt University. November 28, 2016

“Cigarette Smoking and Cause-Specific Mortality in the United States.” Population, Health, and Education Center, University of Missouri. November 10, 2016

“Hispanic-White Differences in Lifespan Variability.” CUNY Institute for Demographic Research, City University of New York. May 6, 2016

“Hispanic Adult Mortality in the United States: New Estimates and an Assessment of Factors Shaping the Hispanic Paradox.” Department of Demography, University of Texas at San Antonio. November 10, 2014 

“Racial and Ethnic Inequality in Adult Survival in the United States.” Department of Sociology, Duke University. September 12, 2014

“The Significance of Differential Record Linkage for Understanding Black-White Survival Inequality.” Texas Census Research Data Center, Texas A&M University. April 18, 2013

# Selected Presentations at Professional Meetings

*ASA = American Sociological Association, IAPHS = Interdisciplinary Association for Population Health Sciences, PAA = Population Association of America, SDA = Southern Demographic Association, SSS = Southern Sociological Society*

Joseph T. Lariscy. "Cause-of-Death Contributions to the Hispanic Paradox: Before, During, and After the COVID-19 Pandemic." SDA, October 19, 2023

Joseph T. Lariscy and Eric Vogelsang. “Racial/Ethnic Disparities in Lifespan Variability in the United States, 2019 and 2020." (poster). PAA, April 14, 2023

Joseph T. Lariscy and Eric Vogelsang. “Racial/Ethnic Disparities in Lifespan Variability before and during the COVID-19 Pandemic." SDA, October 18, 2022

Joseph T. Lariscy and Eric Vogelsang. “Racial/Ethnic Disparities in Life Expectancy and Lifespan Variability in the United States” (poster). PAA, April 7, 2022

Joseph T. Lariscy and Eric Vogelsang. “Racial/Ethnic Disparities in Mortality Compression and Rectangularization in the United States.” ASA (virtual), August 9, 2021

Brown, Dustin C., Joseph T. Lariscy, and Benjamin Walker. “State-Level Trends in Lifespan Variability in the United States between 1960 and 2014.” PAA (virtual), May 5, 2021

Brown, Dustin C., Joseph T. Lariscy, and Benjamin Walker. “State-Level Trends in Lifespan Variability in the United States between 1960 and 2014.” Accepted for presentation at 2020 PAA meeting, Washington, DC (conference canceled due to COVID-19 virus)

Fatema, Kaniz and Joseph T. Lariscy. “Mass Media Exposure and Maternal Healthcare Utilization in South Asia.” Accepted for poster at 2020 PAA meeting, Washington, DC (conference canceled due to COVID-19 virus)

Vogelsang, Eric and Joseph T. Lariscy. “Let’s Drink to Being Social: Family Characteristics, Social Participation, and Alcohol Abuse across Mid- and Later-Life.” Accepted for presentation at 2020 PAA meeting, Washington, DC (conference canceled due to COVID-19 virus)

Brown, Dustin C., Joseph T. Lariscy, and Benjamin Walker. “State-Level Trends in Lifespan Variability in the United States between 1960 and 2014.” Accepted for presentation at 2020 SSS meeting, Jacksonville, FL (conference canceled due to COVID-19 virus)

Brown, Dustin C., Joseph T. Lariscy, and Benjamin Walker. “State-Level Trends in Lifespan Variability in the United States between 1960 and 2014.” IAPHS, Seattle, WA, October 3, 2019

Lariscy, Joseph T, Robert A. Hummer, and Richard G. Rogers. “Lung Cancer Mortality among Nonsmokers: Estimating Smoking-Attributable Mortality with Nationally-Representative Data” (poster). PAA, Austin, TX, April 11, 2019

Lariscy, Joseph T, Robert A. Hummer, and Richard G. Rogers. “Lung Cancer Mortality among Nonsmokers: Estimating Smoking-Attributable Mortality with Nationally-Representative Data.” SDA, Durham, NC, October 11, 2018

Lariscy, Joseph T. “Smoking-Attributable Mortality by Cause of Death: An Indirect Approach.” PAA, Denver, CO, April 26, 2018

Lariscy, Joseph T. “Identifying Smoking-Attributable Causes of Death: A New Application of the Preston-Glei-Wilmoth Model.” 2017 SDA, Morgantown, WV, October 27, 2017

Lariscy, Joseph T. “Paradox by Number: Mortality Compression and Rectangularization among U.S. Hispanics” (poster). PAA, Chicago, IL, April 27, 2017

Lariscy, Joseph T. “Paradox by Number: Mortality Compression and Rectangularization among U.S. Hispanics.” SDA, Athens, GA, October 13, 2016

Brown, Dustin C., Joseph T. Lariscy, and Lucie Kalousova. “A Comparison of Mortality Estimates from Multiple Nationally Representative Surveys and Vital Statistics Data in the United States.” PAA, Washington, DC, April 1, 2016

Lariscy, Joseph T., Robert A. Hummer, Richard G. Rogers, and Charles B. Nam. “Cigarette Smoking and Cause-Specific Mortality in the United States.” PAA, Washington, DC, March 31, 2016

Lariscy, Joseph T., Robert A. Hummer, Richard G. Rogers, and Charles B. Nam. “Cigarette Smoking and Cause-Specific Mortality in the United States.” SDA, San Antonio, TX, October 15, 2015

Lariscy, Joseph T. “The Long Plume of Childhood: Cigarette Smoking throughout the Life Course and Racial/Ethnic Mortality Differentials” (round table). ASA, San Francisco, CA, August 19, 2014

Lariscy, Joseph T. Implications of Differential Record Linkage for Understanding the Black-White Mortality Gap” (poster). PAA, Boston, MA, May 3, 2014

Lariscy, Joseph T. “The Significance of Differential Record Linkage for Understanding Black-White Survival Inequality.” SDA, Montgomery, AL, October 25, 2013

Lariscy, Joseph T. “The Significance of Differential Record Linkage for Understanding Black-White Survival Inequality.” ASA, New York, NY, August 11, 2013

Lariscy, Joseph T., Claudia Nau, Glenn Firebaugh, and Robert A. Hummer. “Racial and Ethnic Inequality in Adult Survival: Decomposition of Age at Death Variance among U.S. Adults.” PAA, New Orleans, LA, April 11, 2013

Lariscy, Joseph T., Claudia Nau, Glenn Firebaugh, and Robert A. Hummer. “Racial and Ethnic Inequality in Adult Survival: Decomposition of Age at Death Variance among U.S. Adults.” SDA, Williamsburg, VA, October 11, 2012

Lariscy, Joseph T. “The Long Plume of Childhood: Cigarette Smoking throughout the Life Course and Adult Mortality Differentials.” PAA, San Francisco, CA, May 4, 2012

Lariscy, Joseph T. “The Long Plume of Childhood: Cigarette Smoking throughout the Life Course and Adult Mortality Differentials.” SDA, Tallahassee, FL, October 20, 2011

Lariscy, Joseph T., Kristine Hopkins, and Rachel Samsel. “Acculturation and Parent-Adolescent Communication about Sex among Mexican-Origin Families.” ASA, Las Vegas, NV, August 20, 2011

Hummer, Robert A., Joseph T. Lariscy, and Mark D. Hayward. “Hispanic Adult Mortality in the United States: A Review, New Estimates, and Comparisons to Other Population Groups.” MacArthur Foundation Research Network on an Aging Society, Palo Alto, CA, February 14, 2011

Lariscy, Joseph T. “Race/Ethnicity and US Adult Mortality: An Examination of Vital Status Ascertainment in the National Health Interview Survey Linked Mortality Files.” SDA, Galveston, TX, October 23, 2009

Lariscy, Joseph T. “Latino Healthcare Coverage in an Emerging Gateway Southern State.” SDA, Durham, NC, November 3, 2006

# Teaching

*University of Memphis*

\setlength{\leftskip}{0.5cm}
| Graduate:  
\setlength{\leftskip}{0pt}
\setlength{\leftskip}{1cm}
| SOCI 7612 – Social Demography (fall 2023, spring 2021, spring 2018)  
| SOCI 7851/8851 – Medical Sociology (fall 2016)  
| SOCI 6312 – Intermediate Social Statistics (spring 2024, spring 2023, spring 2022,   
|      spring 2021, spring 2020, spring 2019, spring 2018, spring 2017, spring 2016)  

\setlength{\leftskip}{0pt}

\setlength{\leftskip}{0.5cm}
| Undergraduate:  
\setlength{\leftskip}{0pt}
\setlength{\leftskip}{1cm}
| SOCI 3311 – Social Statistics (fall 2023, spring 2020, fall 2019, fall 2018, fall 2017,   
|     spring 2017, fall 2016, fall2015)  
| SOCI 3422 – Racial and Ethnic Minorities (fall 2022, spring 2019, fall 2018)  
| SOCI 4541 – Sociology of Aging (fall 2020)  
| SOCI 4851 – Medical Sociology (fall 2022, fall 2019, fall 2017)  
| UNHP 1100 – Census 2020: How the United States Counts its Diverse Population (fall 2019)  
\setlength{\leftskip}{0pt}

*University of Texas at Austin*

\setlength{\leftskip}{1cm}
| SOC 319 – Introduction to Social Demography (fall 2011)  
\setlength{\leftskip}{0pt}

# Honors and Awards

2021 &nbsp; &nbsp; &nbsp; Professional Development Assignment, University of Memphis  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Research leave for Fall 2021 semester

2020 &nbsp; &nbsp; &nbsp; Open Access Grant; Fine Arts, Humanities, & Social Science Pilot Program;  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; University of Memphis  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; $3,270 for Gold Open Access fees

2015–16	&nbsp;Professional Development Support, Carolina Population Center,  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; University of North Carolina-Chapel Hill  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; $1,950 to conduct analyses at the Triangle Federal Statistical Research Data Center

2015 &nbsp; &nbsp; &nbsp; IPUMS Health Surveys Research Award, Minnesota Population Center  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; *Hispanic Older Adult Mortality in the United States: New Estimates and an Assessment of*  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; *Factors Shaping the Hispanic Paradox*, with Robert Hummer and Mark Hayward

2013–15	&nbsp;Postdoctoral Fellowship, Duke Population Research Institute  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; T32 Training Grant in the Social, Medical, and Economic Demography of Aging,  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; funded by the National Institute on Aging

2013 &nbsp; &nbsp; &nbsp; Texas Census Research Data Center Proposal Development Grant ($500)  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; $500 to assist with data linkage fees

2012–13	&nbsp;Sociology Continuing Fellowship  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Dissertation fellowship awarded by University of Texas Graduate School ($23,800)

2012 &nbsp; &nbsp; &nbsp; Doug Forbes Research Development Award, awarded by PRC Training Committee  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; $1,000 to conduct analyses at the Texas Census Research Data Center

\newpage

2011 &nbsp; &nbsp; &nbsp; Everett S. Lee Graduate Student Paper Award  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; *The Long Plume of Childhood: Cigarette Smoking throughout the Life* Course and Adult  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; *Mortality Differentials*  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Awarded by the Southern Demographic Association

2011 &nbsp; &nbsp; &nbsp; Doug Forbes Research Development Award  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Awarded by Population Research Center Training Committee, University of Texas at  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Austin  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; $1,075 award to attend Cells2Society Biomarkers Institute, Northwestern University

2010–11	&nbsp;Ruth L. Kirschstein National Research Service Award Pre-doctoral Traineeship  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Traineeship awarded by Population Research Center Training Committee,  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; University of Texas at Austin and funded by NICHD ($22,180)

2007 &nbsp; &nbsp; &nbsp; David Bruton, Jr. Graduate Fellowship  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Awarded by Population Research Center Training Committee, University of Texas at  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Austin

2007 &nbsp; &nbsp; &nbsp; Elected to Phi Beta Kappa  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; University of Georgia

2005–06	&nbsp;President, Alpha Kappa Delta Sociological Honor Society  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Department of Sociology, University of Georgia

# Professional Development

2013–22 &nbsp;Research Associate, Federal Statistical Research Data Centers  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Special Sworn Status granted July 2013  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Locations: Texas RDC (College Station, TX), Triangle RDC (Durham, NC), and  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Missouri RDC (Columbia, MO)  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Center for Economic Studies, U.S. Census Bureau, U.S. Department of Commerce  

2016 &nbsp; &nbsp; &nbsp; Workshop on Formal Demography (5 days)  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Berkeley Population Center and Center on the Economics and Demography of Aging,  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; University of California, Berkeley

2014 &nbsp; &nbsp; &nbsp; Summer Training Workshop on African American Aging Research (3 days)  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Michigan Center for Urban African American Aging Research, University of Michigan

2012 &nbsp; &nbsp; &nbsp; RAND Summer Institute (4 days)  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Center for the Study of Aging, RAND Corporation

2012 &nbsp; &nbsp; &nbsp; Stanford Workshop in Formal Demography (3 days)  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Institute for Research in the Social Sciences, Stanford University

2011 &nbsp; &nbsp; &nbsp; Cells2Society Summer Biomarkers Institute (3 days)  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Center on Social Disparities in Health, Northwestern University

2009 &nbsp; &nbsp; &nbsp; Longitudinal Data Analysis (4 days)  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Summer Statistics Institute, University of Texas at Austin

2007 &nbsp; &nbsp; &nbsp; National Institute on Aging Population Health and Aging Program (8 weeks)  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Demographic Research Laboratory, Western Washington University

2006 &nbsp; &nbsp; &nbsp; National Science Foundation Research Experience for Undergraduates (10 weeks)  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Research Center, University of Texas at Austin

# Advising

## *Master’s Thesis Chair*

\setlength{\leftskip}{0.5cm}
| Current students and expected graduation
\setlength{\leftskip}{0pt}
\setlength{\leftskip}{1cm}
| Samira Rahman (2024)
| Ivonne Amill-Rosario (2024)
| Purba Bhattacharjee (2024)
\setlength{\leftskip}{0pt}

\setlength{\leftskip}{0.5cm}
| Students completed and position after graduation
\setlength{\leftskip}{0pt}
\setlength{\leftskip}{1cm}
| Israt Jahan (2022) – PhD student, Dept of Sociology, University of Illinois, Urbana-  
|     Champaign
| Sarah Collins (2020) – PhD student, Dept of Sociology, University of Cincinnati
| Aisha Naantaanbuu (2020) – Digital Content Producer, WMC Action News 5
| Kaniz Fatema (2019) – PhD student, Dept of Sociology, University of Iowa
| Dontarious Cowans (2019) – Data Analyst, RELY Workforce Group
| Caleb Cooley (2018) – PhD student, Dept of Sociology, Washington State University
| Daisy Angeles (2017) – Bilingual Community Outreach Specialist, Freedom Preparatory  
|     Academy Charter Schools
| Melissa Garcia-Dominguez (2017) – PhD student, Dept of Sociology, Indiana University
\setlength{\leftskip}{0pt}

## *Master’s Thesis Committee Member*

\setlength{\leftskip}{0.5cm}
| Current students and expected graduation
\setlength{\leftskip}{0pt}
\setlength{\leftskip}{1cm}
| Rifat Jahan Loran (2023)
\setlength{\leftskip}{0pt}

\setlength{\leftskip}{0.5cm}
| Students completed and position after graduation
\setlength{\leftskip}{0pt}
\setlength{\leftskip}{1cm}
| Melissa Arismendy (2022)
| Clarion Harris (2022)
| Ebenezer Kpuinen (2021)
| Uyvonda Stewart (2021) – Adjunct Instructor, Dept of Sociology, University of Memphis
| Michael Topping (2020) – PhD student, Dept of Sociology, University of Wisconsin
| Anna Church (2019) – PhD student, Dept of Sociology, Ohio State University
| Hannah Pallotta (2019) – Research Associate, Shelby County Schools
| Samia Tasmim (2019) – PhD student, Dept of Sociology, Stony Brook University
| Krista Wright Thayer (2018) – PhD student, Schol of Urban Affiars and Public Policy, University of Memphis
\setlength{\leftskip}{0pt}

# Professional Service

\underline{Reviewer}  
*American Journal of Sociology*, *American Sociological Review*, *Annals of Epidemiology*, *Biodemography and Social Biology*, *BMJ Open*, *Demographic Research*, *Demography*, *Epidemiology*, *Ethnicity and Health*, *Innovations in Aging*, *International Migration Review*, *Journal of Aging and Health*, *Journal of Gerontology: Series B*, *Journal of Health and Social Behavior*, *Journal of Immigrant and Minority Health*, *Journal of Racial and Ethnic Disparities*, *Nicotine and Tobacco Research*, *PLoS One*, *Population Research and Policy Review*, *Population Studies*, *Research on Aging*, *Social Currents*, *Social Forces*, *Social Science & Medicine*, *Social Science & Medicine–Population Health*, *Social Science Research*, *Sociological Quarterly*, *Sociological Science*, *Sociological Spectrum*, *Sociology of Race and Ethnicity*, *Socius*

\underline{Service to University of Memphis}  
2022–present &nbsp;Webmaster, Department of Sociology  
2023 (fall)	&nbsp; &nbsp; &nbsp; Member, Faculty Search Committee, Department of Sociology  
2023 (summer)	&nbsp;Chair, Teaching Faculty Search Committee (two positions), Department of  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Sociology  
2023 (spring)	&nbsp;Comprehensive Exam Committee, Department of Sociology  
2022 (fall)	&nbsp; &nbsp; &nbsp; Chair, Faculty Search Committee, Department of Sociology  
2022 (summer)	&nbsp;Postdoctoral Fellow Search Committee, Department of Sociology  
2020–present &nbsp;Director of Graduate Studies, Department of Sociology  
2015–present &nbsp;Graduate Committee, Department of Sociology  
2021 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Reviewer, Student Research Forum  
2021 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Graduate Awards Sub-committee, Graduate Council  
2021 (spring)	&nbsp;Comprehensive Exam Committee, Department of Sociology  
2020 (fall)	&nbsp; &nbsp; &nbsp; Comprehensive Exam Committee, Department of Sociology  
2020 (spring)	&nbsp;Comprehensive Exam Committee, Department of Sociology  
2019 (summer)	&nbsp;Postdoctoral Fellow Search Committee, Department of Sociology  
2018 (spring)	&nbsp;Comprehensive Exam Committee, Department of Sociology  
2017 (fall)	&nbsp; &nbsp; &nbsp; Faculty Search Committee (two tenure-track positions), Department of Sociology  
2017 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Moderator, National Conference on Undergraduate Research  
2016 (spring)	&nbsp;Comprehensive Exam Committee, Department of Sociology

\underline{Service to Professional Organizations}  
2022–present &nbsp;Webmaster, Southern Demographic Association   
2021–23 &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp;Nominations Committee, Southern Sociological Society  
2022–23 &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp;Program Committee, Section on Sociology of Population, American Sociological  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Association  
2022–23 &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp;Program Committee, Section on Aging and the Life Course, American Sociological  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Association  
2018–19 &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp;Student Paper Competition Committee, Southern Demographic Association  
2021 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Program Committee and Chair of Sub-committee on Mortality and Morbidity,  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting  
2016–18 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Member, Board of Directors, Southern Demographic Association (three-year term)  

\underline{Service to Discipline}  
2021–23 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Editorial Board, *Journal of Health and Social Behavior*  
2018–present &nbsp;Member, CenSoc Advisory Panel (PI: Joshua Goldstein, UC, Berkeley)  
2023 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Chair, “Health and Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; American Sociological Association  
2023 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Organizer, “Health and Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; American Sociological Association  
2023 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Chair, “Gender Disparities in Health: Mechanisms and Pathways”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America  
2023 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Discussant, “National/Subnational Comparisons of COVID-19 Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America  
2022 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Co-Chair, “Biosocial Approaches to Population Health”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America  
2022 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Co-Chair, “Old Wine in New Bottles: Tools for Applied Demographers”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America  
2021 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Presider, “Morbidity and Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; American Sociological Association meeting  
2021 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Organizer, “Morbidity and Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; American Sociological Association meeting  
2021 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Discussant, “Immigration, Health, and Social Context”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting  
2021 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Chair, “Socioeconomic Status and Mortality in Europe”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting  
2021 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Chair, “Smoking, Health, and Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting  
2021 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Presider, “Health Policy”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Southern Sociological Society meeting (virtual)  
2021 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Organizer, “Smoking, Health, and Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting  
2020 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Discussant, “Maternal Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting (canceled due to COVID-19)  
2020 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Chair, “Smoking, Health, and Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting (canceled due to COVID-19)  
2020 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Organizer, “Smoking, Health, and Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting (canceled due to COVID-19)  
2019 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Discussant, “Migration and Health/Well-being”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting  
2018 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Chair, “Causes of Infant and Neonatal Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Southern Demographic Association meeting  
2018 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Discussant, “Race, Ethnicity, and Population Health”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting  
2018 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Chair, “Disparities in Birth Outcomes in the U.S.”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting  
2017 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Chair, “Health and Maternal Behaviors”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Southern Demographic Association meeting  
2017 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Poster Session Judge, “Health and Mortality 3”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Population Association of America meeting  
2016 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Chair, “Latino/a Health”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Southern Demographic Association meeting  
2015 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Chair, “Race/Ethnic Differences in Mortality”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Southern Demographic Association meeting  
2013 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Session Chair, “Aging Populations in the United States, Japan, and Korea”  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Southern Demographic Association meeting  
2013 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Program Committee, 2013 REVES Network meeting  
2010–13 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Graduate Student Mentor, National Science Foundation Research Experience for  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Undergraduates  
2010 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Program Committee, Southern Demographic Association  
2010 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Local Arrangements Committee, Population Association of America  

\newpage

# Professional Memberships

| American Sociological Association, 2005–present  
\setlength{\leftskip}{0.75cm}
| *Sections:* Aging and the Life Course; Medical Sociology; Sociology of Population   
\setlength{\leftskip}{0pt}
Population Association of America, 2008–present  
Southern Demographic Association, 2006–present  
Southern Sociological Society, 2007–present  

# References

Robert A. Hummer, Ph.D.  
Howard W. Odum Professor of Sociology  
University of North Carolina at Chapel Hill  
206 West Franklin Street, Room 211  
Chapel Hill, NC 27516  
rhummer@email.unc.edu
  
Mark D. Hayward, Ph.D.  
Professor of Sociology and  
Centennial Commission Professor of Liberal Arts  
University of Texas at Austin  
305 East 23rd Street, G1800  
Austin, TX 78712  
mhayward@prc.utexas.edu
  
Anna Mueller, Ph.D.  
Luther Dana Waterman Associate Professor of Sociology  
Indiana University  
Ballantine Hall 764  
Bloomington, IN 47405  
mueller1@iu.edu
